version: "3.8"

services:
  database-injector:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    container_name: database-injector
    image: emissions-server
    tty: true
    volumes:
      - ../src:/usr/src/app:ro
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_FILE=${DATABASE_FILE}
    command: ["npm", "run", "inject-data"]