version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    # restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # emissions-server:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile.server
  #   container_name: emissions-server
  #   image: emissions-server
  #   tty: true
  #   # restart: always
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ../src:/usr/src/app:ro
  #     - /usr/src/app/node_modules
  #   environment:
  #     - SERVER_PORT=5000
  #     - DATABASE_URL=mongodb://mongodb:27017/greenhouse
  #   depends_on:
  #     - mongodb

volumes:
  mongo-data: