GET http://localhost:5000/api/countries

###
POST http://localhost:5000/api/countries
Content-Type: application/json

{
    "name": "Thailand",
    "code": "THA"
}

###
GET http://localhost:5000/api/emissions?country=THA&year=1998

###
POST http://localhost:5000/api/emissions
Content-Type: application/json

{
    "country": {
        "name": "Thailand",
        "code": "THA"
    },
    "year": 12345,
    "total_value": 1235845.45845,
    "gases": [
        {
            "name": "Carbon Dioxide",
            "code": "CO2",
            "total_value": 0,
            "sectors": [
                {
                    "name": "Haidilao",
                    "code": "AG",
                    "value": 0
                },
                {
                    "name": "Hello",
                    "code": "TRAN"
                },
                {
                    "name": "Kagonoya",
                    "code": "OTHX",
                    "value": 0
                }
            ]
        },
        {
            "name": "Nitrous Oxide",
            "code": "N2O"
        }
    ]
}

###
GET http://localhost:5000/api/emissions/sector?country=THA&year=1998

###
GET http://localhost:5000/api/emissions/sector?country=THA&year=1998&gas=CO2

###
GET http://localhost:5000/api/emissions/trend?country=THA

###
GET http://localhost:5000/nus/sd/trend?country=THAdfasdf&asdbasd=jhsadf